export enum EnumOrderStatus {
  CREATED = 'CREATED',
  CANCELLED_BY_CUSTOMER = 'CANCELLED_BY_CUSTOMER',
  PAYMENT_INITIATED = 'PAYMENT_INITIATED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAID = 'PAID',
  CANCELLED_BY_RESTAURANT = 'CANCELLED_BY_RESTAURANT',
  PREPARING_ORDER = 'PREPARING_ORDER',
  IN_DELIVERY = 'IN_DELIVERY',
  DELIVERED = 'DELIVERED',
  DISBURSED = 'DISBURSED',
}
